gitsrht/urls.py
from flask import url_for
from srht.config import cfg, get_origin

def clone_urls(repo):
    """Returns the readonly and read/write URL for a given repo."""
    git_user = cfg("git.sr.ht::dispatch", "/usr/bin/git.sr.ht-keys", "git:git").split(":")[0]
    base = (get_origin("git.sr.ht", external=True)
        .replace("http://", "")
        .replace("https://", ""))
    return [
        url.format(base, repo.owner.canonical_name, repo.name)
        for url in ["https://{}/{}/{}", git_user+"@{}:{}/{}"]
    ]

def log_rss_url(repo, ref=None):
    ref = ref if ref != repo.git_repo.default_branch_name() else None
    return url_for("repo.log_rss",
        owner=repo.owner.canonical_name,
        repo=repo.name,
        ref=ref)

def refs_rss_url(repo):
    return url_for("repo.refs_rss",
        owner=repo.owner.canonical_name,
        repo=repo.name)

gitsrht/blueprints/artifacts.py
import hashlib
import os
import pygit2
from flask import Blueprint, redirect, render_template, request, redirect
from flask import abort, url_for, send_file
from gitsrht.git import Repository as GitRepository, strip_pgp_signature
from gitsrht.repos import delete_artifact, upload_artifact
from gitsrht.types import Artifact
from minio import Minio
from gitsrht.access import check_access, UserAccess
from srht.config import cfg
from srht.database import db
from srht.oauth import loginrequired
from srht.validation import Validation
from werkzeug.utils import secure_filename

artifacts = Blueprint('artifacts', __name__)

s3_upstream = cfg("objects", "s3-upstream", default=None)
s3_access_key = cfg("objects", "s3-access-key", default=None)
s3_secret_key = cfg("objects", "s3-secret-key", default=None)
s3_secure = cfg("objects", "s3-insecure", default="no") != "yes"
s3_bucket = cfg("git.sr.ht", "s3-bucket", default=None)
s3_prefix = cfg("git.sr.ht", "s3-prefix", default=None)

@artifacts.route("/<owner>/<repo>/refs/upload/<path:ref>", methods=["POST"])
@loginrequired
def ref_upload(owner, repo, ref):
    owner, repo = check_access(owner, repo, UserAccess.manage)
    with GitRepository(repo.path) as git_repo:
        try:
            tag = git_repo.revparse_single(ref)
        except KeyError:
            abort(404)
        except ValueError:
            abort(404)
        if isinstance(tag, pygit2.Commit):
            target = str(tag.id)
        else:
            target = str(tag.target)
        valid = Validation(request)
        valid.expect(request.files.get("file"), "File is required", field="file")
        file_list = request.files.getlist("file")
        default_branch = git_repo.default_branch()
        if not valid.ok:
            return render_template("ref.html", view="refs",
                    owner=owner, repo=repo, git_repo=git_repo, tag=tag,
                    strip_pgp_signature=strip_pgp_signature,
                    default_branch=default_branch, **valid.kwargs)
        for f in file_list:
            artifact = upload_artifact(valid, repo, target, f, f.filename)
            if not valid.ok:
                return render_template("ref.html", view="refs",
                        owner=owner, repo=repo, git_repo=git_repo, tag=tag,
                        strip_pgp_signature=strip_pgp_signature,
                        default_branch=default_branch, **valid.kwargs)
        db.session.commit()
        return redirect(url_for("repo.ref",
            owner=owner.canonical_name,
            repo=repo.name,
            ref=ref))

@artifacts.route("/<owner>/<repo>/refs/download/<path:ref>/<filename>")
def ref_download(owner, repo, ref, filename):
    owner, repo = check_access(owner, repo, UserAccess.read)
    with GitRepository(repo.path) as git_repo:
        try:
            tag = git_repo.revparse_single(ref)
        except KeyError:
            abort(404)
        except ValueError:
            abort(404)
        if isinstance(tag, pygit2.Commit):
            target = str(tag.id)
        else:
            target = str(tag.target)
    artifact = (Artifact.query
            .filter(Artifact.user_id == owner.id)
            .filter(Artifact.repo_id == repo.id)
            .filter(Artifact.commit == target)
            .filter(Artifact.filename == filename)).one_or_none()
    if not artifact:
        abort(404)
    prefix = os.path.join(s3_prefix, "artifacts",
            repo.owner.canonical_name, repo.name)
    minio = Minio(s3_upstream, access_key=s3_access_key,
            secret_key=s3_secret_key, secure=s3_secure)
    f = minio.get_object(s3_bucket, os.path.join(prefix, filename))
    resp = send_file(f, as_attachment=True, download_name=filename)
    resp.headers.add("Content-Length", f.getheaders()["Content-Length"])
    return resp

@artifacts.route("/<owner>/<repo>/refs/delete/<path:ref>/<filename>", methods=["POST"])
@loginrequired
def ref_delete(owner, repo, ref, filename):
    owner, repo = check_access(owner, repo, UserAccess.manage)
    with GitRepository(repo.path) as git_repo:
        try:
            tag = git_repo.revparse_single(ref)
        except KeyError:
            abort(404)
        except ValueError:
            abort(404)
        if isinstance(tag, pygit2.Commit):
            target = str(tag.id)
        else:
            target = str(tag.target)
    artifact = (Artifact.query
            .filter(Artifact.user_id == owner.id)
            .filter(Artifact.repo_id == repo.id)
            .filter(Artifact.commit == target)
            .filter(Artifact.filename == filename)).one_or_none()
    if not artifact:
        abort(404)
    delete_artifact(artifact)
    db.session.commit()
    return redirect(url_for("repo.ref",
        owner=owner.canonical_name, repo=repo.name, ref=ref))

gitsrht/blueprints/public.py
from flask import Blueprint, current_app, request
from flask import render_template, abort
from srht.config import cfg
from srht.flask import paginate_query
from srht.oauth import current_user
from srht.search import search_by
from gitsrht.types import Access, Repository, User, Visibility
from sqlalchemy import and_, or_

public = Blueprint('public', __name__)

@public.route("/")
def index():
    if current_user:
        repos = (Repository.query
                .filter(Repository.owner_id == current_user.id)
                .order_by(Repository.updated.desc())
                .limit(10)).all()
        return render_template("dashboard.html", repos=repos)
    return render_template("index.html")

@public.route("/~<username>")
@public.route("/~<username>/")
def user_index(username):
    user = User.query.filter(User.username == username).first()
    if not user:
        abort(404)
    terms = request.args.get("search")
    repos = (Repository.query
            .filter(Repository.owner_id == user.id))
    if current_user and current_user.id != user.id:
        repos = (repos
                .outerjoin(Access,
                    Access.repo_id == Repository.id)
                .filter(or_(
                    Access.user_id == current_user.id,
                    Repository.visibility == Visibility.PUBLIC,
                )))
    elif not current_user:
        repos = repos.filter(Repository.visibility == Visibility.PUBLIC)

    search_error = None
    try:
        repos = search_by(repos, terms,
                [Repository.name, Repository.description])
    except ValueError as ex:
        search_error = str(ex)

    repos = repos.order_by(Repository.updated.desc())
    repos, pagination = paginate_query(repos)

    return render_template("user.html",
            user=user, repos=repos,
            search=terms, search_error=search_error, **pagination)

gitsrht/blueprints/repo.py
import binascii
import json
import os
import pygit2
import pygments
import subprocess
import sys
from datetime import datetime, timedelta
from flask import Blueprint, render_template, abort, current_app, send_file, make_response, request
from flask import Response, url_for, session, redirect
from gitsrht.editorconfig import EditorConfig
from gitsrht.git import Repository as GitRepository, commit_time, annotate_tree
from gitsrht.git import diffstat, get_log, diff_for_commit, strip_pgp_signature
from gitsrht.rss import generate_refs_feed, generate_commits_feed
from gitsrht.spdx import SPDX_LICENSES
from gitsrht.types import Artifact, User
from io import BytesIO
from markupsafe import Markup, escape
from jinja2.utils import url_quote
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import guess_lexer, guess_lexer_for_filename, TextLexer
from gitsrht.access import get_repo, get_repo_or_redir
from scmsrht.formatting import get_formatted_readme, get_highlighted_file
from scmsrht.urls import get_clone_urls
from srht.config import cfg, get_origin
from srht.markdown import markdown, sanitize
from srht.oauth import loginrequired
from urllib.parse import urlparse

repo = Blueprint('repo', __name__)

def get_license_info_for_tip(tip):
        license_exists = False
        licences_names = ["LICENSES", "licenses", "LICENCES", "licences"]
        for path in [
                "LICENSE", "LICENCE", "COPYING",
                "LICENSE.txt", "license.txt",
                "LICENCE.txt", "licence.txt",
                "COPYING.txt", "copying.txt",
                "COPYRIGHT.txt", "copyright.txt",
                "LICENSE.md", "license.md",
                "LICENCE.md", "licence.md",
                "COPYING.md", "copying.md",
                "COPYRIGHT.md", "copyright.md",
                "COPYRIGHT", "copyright",
        ] + licences_names:
            if path in tip.tree:
                license_exists = True
                break

        licenses = []
        for lic in licences_names:
            if lic in tip.tree and isinstance(tip.tree[lic], pygit2.Tree):
                for o in tip.tree[lic]:
                    license_id = o.name
                    if license_id not in SPDX_LICENSES:
                        license_id = os.path.splitext(o.name)[0]
                    if license_id in SPDX_LICENSES:
                        licenses.append({
                            'id': license_id,
                            'name': SPDX_LICENSES[license_id],
                        })
                break

        return license_exists, licenses

def get_readme(repo, git_repo, tip, link_prefix=None):
    if repo.readme is not None:
        return Markup(sanitize(repo.readme))

    if not tip:
        return None

    def file_finder(name):
        try:
            blob = tip.tree[name]
        except KeyError:
            return None, None

        if blob:
            btype = (blob.type_str
                    if hasattr(blob, "type_str") else blob.type)
            if btype == "blob":
                return str(blob.id), blob
        return None, None

    def content_getter(blob):
        return git_repo.get(blob.id).data.decode()

    return get_formatted_readme("git.sr.ht:git", file_finder, content_getter,
            link_prefix=link_prefix)

def _highlight_file(repo, ref, entry, data, blob_id, commit_id):
    link_prefix = url_for('repo.tree', owner=repo.owner,
            repo=repo.name, ref=ref)
    if entry.filemode == pygit2.GIT_FILEMODE_LINK:
        return Markup("<div class=\"highlight\"><pre>" +
                f"<a href=\"{url_quote(data.encode('utf-8'))}\">" +
                f"{escape(data)}</a><pre></div>")
    else:
        return get_highlighted_file("git.sr.ht:git", entry.name, blob_id, data)

def linecounter(count):
    out = []
    for i in range(1, count + 1):
        out.append(f'<a href="#L{i}" id="L{i}">{i}\n</a>')
    return "".join(out)

def render_empty_repo(owner, repo, view):
    origin = cfg("git.sr.ht", "origin")
    git_user = cfg("git.sr.ht::dispatch", "/usr/bin/git.sr.ht-keys", "git:git").split(":")[0]
    urls = get_clone_urls(origin, owner, repo, git_user + '@{origin}:{user}/{repo}')
    return render_template("empty-repo.html", owner=owner, repo=repo, view=view,
            clone_urls=urls)

def get_last_3_commits(git_repo, commit):
    commits = list()
    for c in git_repo.walk(commit.id, pygit2.GIT_SORT_NONE):
        commits.append(c)
        if len(commits) >= 3:
            break
    return commits

@repo.route("/<owner>/<repo>")
def summary(owner, repo):
    owner, repo = get_repo_or_redir(owner, repo)

    with GitRepository(repo.path) as git_repo:
        if git_repo.is_empty:
            return render_empty_repo(owner, repo, "summary")

        default_branch = git_repo.default_branch()
        default_branch_name = default_branch.raw_name \
            .decode("utf-8", "replace")[len("refs/heads/"):]
        tip = git_repo.get(default_branch.raw_target)
        commits = get_last_3_commits(git_repo, tip)
        link_prefix = url_for(
            'repo.tree', owner=repo.owner, repo=repo.name,
            ref=f"{default_branch_name}/")  # Trailing slash needed
        blob_prefix = url_for(
            'repo.raw_blob', owner=repo.owner, repo=repo.name,
            ref=f"{default_branch_name}/", path="")  # Trailing slash needed
        readme = get_readme(repo, git_repo, tip,
            link_prefix=[link_prefix, blob_prefix])
        tags = [(ref, git_repo.get(git_repo.references[ref.decode('utf-8')].raw_target))
            for ref in git_repo.raw_listall_references()
            if ref.startswith(b"refs/tags/")]
        tags = [tag for tag in tags
                if (isinstance(tag[1], pygit2.Tag) or isinstance(tag[1], pygit2.Commit))
                and (isinstance(tag[1], pygit2.Commit) or isinstance(tag[1].get_object(), pygit2.Commit))]
        tags = sorted(tags, key=lambda c: commit_time(c[1]), reverse=True)
        latest_tag = tags[0] if len(tags) else None

        message = session.pop("message", None)

        license_exists, licenses = get_license_info_for_tip(tip)

        if latest_tag:
            sig = lookup_signature(git_repo, latest_tag[0].decode('utf-8'))[1]
        else:
            sig = None
        return render_template("summary.html", view="summary",
                owner=owner, repo=repo, readme=readme, commits=commits,
                signature=sig,
                latest_tag=latest_tag, default_branch=default_branch,
                is_annotated=lambda t: isinstance(t, pygit2.Tag),
                message=message, license_exists=license_exists,
                licenses=licenses)

@repo.route("/<owner>/<repo>/<path:path>")
def go_get(owner, repo, path):
    if "go-get" not in request.args:
        abort(404)
    owner, repo = get_repo_or_redir(owner, repo)
    root = get_origin("git.sr.ht", external=True)
    origin = urlparse(root).netloc
    return "".join(['<!doctype html>',
        '<title>Placeholder page for Go import resolution</title>',
        '<meta name="go-import" content="',
            f'{origin}/{owner.canonical_name}/{repo.name} ',
            f'git ',
            f'{root}/{owner.canonical_name}/{repo.name}',
        '" />',
    ])

def lookup_ref(git_repo, ref, path):
    branch = git_repo.default_branch()
    if not branch:
        abort(404)
    ref = ref.encode("utf-8") if ref else branch.raw_name[len(b"refs/heads/"):]
    if not path:
        path = []
    else:
        path = path.split("/")
    commit = None
    try:
        commit = git_repo.revparse_single(ref)
    except KeyError:
        pass
    except ValueError:
        pass
    while commit is None and len(path):
        ref += b"/" + path[0].encode("utf-8")
        path = path[1:]
        try:
            commit = git_repo.revparse_single(ref)
        except KeyError:
            pass
        except ValueError:
            pass
    if commit is None:
        abort(404)
    if isinstance(commit, pygit2.Tag):
        commit = git_repo.get(commit.target)
    if not commit:
        abort(404)
    return commit, ref, "/".join(path)

def lookup_signature(git_repo, ref, fmt=['tar', 'tar.gz']):
    try:
        commit_or_tag = git_repo.revparse_single(ref)
    except (KeyError, ValueError):
        return None, None
    if not isinstance(commit_or_tag, (pygit2.Commit, pygit2.Tag)):
        return None, None

    for trial in fmt:
        try:
            note = git_repo.lookup_note(str(commit_or_tag.id), f'refs/notes/signatures/{trial}')
        except KeyError:
            continue

        return note.message, trial
    return None, None

@repo.route("/<owner>/<repo>/tree", defaults={"ref": None, "path": ""})
@repo.route("/<owner>/<repo>/tree/<path:ref>", defaults={"path": ""})
@repo.route("/<owner>/<repo>/tree/<path:ref>/item/<path:path>")
def tree(owner, repo, ref, path):
    owner, repo = get_repo_or_redir(owner, repo)

    if ref and "/" in ref and not path:
        ref, _, path = ref.partition("/")

    with GitRepository(repo.path) as git_repo:
        if git_repo.is_empty:
            return render_empty_repo(owner, repo, "tree")

        # lookup_ref will cycle through the path to separate
        # the actual ref from the actual path
        commit, ref, path = lookup_ref(git_repo, ref, path)
        refname = ref.decode('utf-8', 'replace')
        if isinstance(commit, pygit2.Tag):
            commit = git_repo.get(commit.target)
        orig_commit = commit
        if not isinstance(commit, pygit2.Commit):
            abort(404)
        tree = commit.tree
        if not tree:
            abort(404)
        editorconfig = EditorConfig(git_repo, tree, path)

        entry = tree
        path = path.split("/")
        for part in path:
            if part == "":
                continue
            if not tree or part not in tree:
                abort(404)
            entry = tree[part]

gitsrht/templates/base.html
{% extends "layout.html" %}

{% block body %}
{% block content %}{% endblock %}
{% endblock %}

gitsrht/templates/blame.html
{% extends "repo-full.html" %}
{% import "utils.html" as utils %}
{% block title %}
<title>{{repo.owner.canonical_name}}/{{repo.name}} ({{ ref }}): {{path_join(*path)}} blame - {{cfg("sr.ht", "site-name")}} git</title>
{% endblock %}
{% block repohead %}
<style>
pre {
  tab-size: {{editorconfig.tab_width()}}
}
pre, body {
  padding-bottom: 0;
  margin-bottom: 0;
}
</style>
{% endblock %}
{% block content %}
<div class="header-extension mb-0">
  <div class="blob container-fluid">
    <span>
      {{ utils.breadcrumb(ref, commit.id, repo, path, entry, view, path_join, stat, pygit2, humanize, current_user) }}
    </span>
    <div class="commit">
      <a
        href="{{url_for("repo.commit",
          owner=repo.owner.canonical_name,
          repo=repo.name,
          ref=str(commit.id))}}"
      >{{str(commit.id)[:8]}}</a> &mdash;
      {% set author_user = lookup_user(commit.author.email) %}
      {% if author_user %}
      <a href="{{url_for("public.user_index",
        username=author_user.username)}}">{{commit.author.name}}</a>
      {% else %}
      {{commit.author.name}}
      {% endif %}
      {{trim_commit(commit.message)}}
      <span class="text-muted">
        {{ commit_time(commit) | date }}
      </span>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container-fluid code-viewport">
  {#
    This row has some weird styles going on. This prevents the page from
    scrolling horizontally
  #}
  <div class="row mr-0">
    <div class="col-md-12 code-view">
      <pre class="ruler"><span>{% for i in range(
        editorconfig.max_line_length()) %} {% endfor %}</span></pre>
      {% set lns = namespace(line_count=0) %}
      <pre class="blame-user">
        {%- for hunk in blame %}
          {%- set lns.line_count = lns.line_count + hunk.lines_in_hunk -%}
          {%- if hunk.final_committer -%}
          {%- set final_user = lookup_user(hunk.final_committer.email) -%}
          {%- else -%}
          {%- set final_user = None -%}
          {%- endif -%}
          <div class="hunk">{#
          #}<a href="{{url_for("repo.commit",
              owner=repo.owner.canonical_name, repo=repo.name,
              ref=str(hunk.final_commit_id))}}"
            >{{str(hunk.final_commit_id)[:8]}}</a> {% if final_user -%}
            <a href="{{url_for("public.user_index", username=final_user.username)}}">{{hunk.final_committer.name}}</a>{% else -%}
            {{hunk.final_committer.name}}{% endif %} {{ "\n" * hunk.lines_in_hunk -}}
          </div>
        {%- endfor -%}
      </pre>
      <pre class="blame-time">
        {%- for hunk in blame -%}
          <div class="hunk">{#
          #}<a
              href="{{url_for("repo.blame", owner=repo.owner.canonical_name,
                repo=repo.name, ref=hunk.final_commit_id,
                path=path_join(*path))}}"
            >{{ commit_time(repo.git_repo[hunk.final_commit_id]) | date }}</a>{{ "\n" * hunk.lines_in_hunk -}}
          </div>
        {%- endfor -%}
      </pre>
      <pre class="lines">{% for l in range(lns.line_count) %}<a
        href="#L{{loop.index}}"
        id="L{{loop.index}}"
        >{{loop.index}}</a>
{% endfor %}</pre>
      {{ highlight_file(repo, ref, entry,
        data, str(blob.id), str(commit.id)) }}
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="/static/linelight.js"></script>
{% endblock %}

gitsrht/templates/ref.html
{% extends "repo.html" %}
{% import "utils.html" as utils %}
{% block title %}
<title>{{repo.owner.canonical_name}}/{{repo.name}} {{tag.name}} - {{cfg("sr.ht", "site-name")}} git</title>
{% endblock %}
{% block content %}
<div class="container">
  <h3>
    {{tag.name}}
    <small class="pull-right text-muted">
      {{signature_time(tag.tagger) | date}}
    </small>
  </h3>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        {% set tagname = tag.name %}
        <a
          class="btn btn-primary btn-block"
          href="{{url_for("repo.archive",
            owner=repo.owner.canonical_name,
            repo=repo.name, ref=tagname, fmt=signature or "tar.gz")}}"
        >.{{ signature or "tar.gz" }} {{icon("caret-right")}}</a>
        {% if signature %}
        <a
          class="btn btn-default btn-block"
          href="{{url_for("repo.archivesig",
            owner=repo.owner.canonical_name,
            repo=repo.name, ref=tagname, fmt=signature)}}"
        >.{{ signature }}.asc {{icon("caret-right")}}</a>
        {% endif %}
        <a
          class="btn btn-default btn-block"
          rel="nofollow"
          href="{{url_for("repo.tree",
            owner=repo.owner.canonical_name,
            repo=repo.name, ref=tagname)}}"
        >browse {{icon("caret-right")}}</a>
      </div>
      {% if object_storage_enabled %}
      {% if any(artifacts) %}
      <div class="event-list">
        {% for artifact in artifacts %}
        <form
          class="event"
          method="POST"
          action="{{url_for("artifacts.ref_delete",
            owner=repo.owner.canonical_name,
            repo=repo.name, ref=tagname,
            filename=artifact.filename)}}"
        >
          <a
            href="{{url_for("artifacts.ref_download",
              owner=repo.owner.canonical_name,
              repo=repo.name, ref=tagname,
              filename=artifact.filename)}}"
            rel="nofollow"
          >{{ artifact.filename }} {{icon('caret-right')}}</a><br />
          <span
            class="text-muted"
            title="{{artifact.checksum}}"
          >{{artifact.checksum}}</span>
          {% if repo.owner == current_user %}
          {{csrf_token()}}
          <button
            type="submit"
            class="btn btn-danger btn-sm pull-right"
          >Delete this file {{icon('caret-right')}}</button>
          {% endif %}
        </form>
        {% endfor %}
      </div>
      {% endif %}
      {% if repo.owner == current_user %}
      <form
        method="POST"
        action="{{url_for('artifacts.ref_upload',
          owner=repo.owner.canonical_name, repo=repo.name, ref=tagname)}}"
        enctype="multipart/form-data"
      >
        {{csrf_token()}}
        <div class="form-group">
          <label for="file">Attach file to this ref</label>
          <input
            type="file"
            name="file"
            id="file"
            multiple
            class="form-control {{valid.cls("file")}}" />
          {{valid.summary("file")}}
        </div>
        <button type="submit" class="btn btn-default pull-right">
          Upload file {{icon('caret-right')}}
        </button>
      </form>
      {% endif %}
      {% endif %}
    </div>
    <div class="col-md-8">
      <div class="event-list">
        <div class="event">
          {% if tag.message %}
          <pre class="pb-0">{{strip_pgp_signature(tag.message)}}</pre>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gitsrht/templates/repo.html
{% extends "layout.html" %}
{% block head %}
{% block repohead %}
{% endblock %}
{% if repo.visibility.value == 'UNLISTED' %}
<meta name="robots" content="noindex">
{% endif %}
{# VCS meta tags #}
<meta name="vcs" content="git">
{% if default_branch %}
{% set default_branch_name = default_branch.raw_name.decode("utf-8", "replace")[len("refs/heads/"):] %}
<meta name="vcs:default-branch" content="{{default_branch_name}}">
{% endif %}
{# NOTE: unauthorized clone URLs should be listed first #}
{% for clone_url in (repo | clone_urls) %}
<meta name="vcs:clone" content="{{clone_url}}">
{% endfor %}
{# Forge meta tags #}
{% set project_root = root + url_for("repo.summary", owner=repo.owner.canonical_name, repo=repo.name) %}
<meta name="forge:summary" content="{{project_root}}">
<meta name="forge:dir" content="{{project_root}}/tree/{ref}/{path}">
<meta name="forge:file" content="{{project_root}}/tree/{ref}/{path}">
<meta name="forge:rawfile" content="{{project_root}}/blob/{ref}/{path}">
<meta name="forge:line" content="{{project_root}}/tree/{ref}/{path}#L{line}">
{# Go meta tags #}
<meta name="go-import" content="{{domain}}/{{owner.canonical_name}}/{{repo.name}} git {{(repo | clone_urls)[0]}}">
{% endblock %}
{% block body %}
<div class="header-tabbed">
  {% if view == "blob" %}
  <div class="container-fluid">
  {% else %}
  <div class="container">
  {% endif %}
    {% block tabs %}
    {% macro link(path, title, alternates=[]) %}
    <a
      class="nav-link {% if view == title or view in alternates %}active{% endif %}"
      href="{{ path }}">{{ title }}</a>
    {% endmacro %}
    <h2>
      <a href="{{ url_for("public.user_index",
        username=owner.username) }}"
      >{{owner.canonical_name}}</a>/<wbr>{{repo.name}}
    </h2>
    <ul class="nav nav-tabs">
      {% if repo.visibility.value != "PUBLIC" %}
      <li
        class="nav-item nav-text vis-{{repo.visibility.value.lower()}}"
        {% if repo.visibility.value == "UNLISTED" %}
        title="This repository is only visible to those who know the URL."
        {% elif repo.visibility.value == "PRIVATE" %}
        title="This repository is only visible to those who were invited to view it."
        {% endif %}
      >
        {% if repo.visibility.value == "UNLISTED" %}
        Unlisted
        {% elif repo.visibility.value == "PRIVATE" %}
        Private
        {% endif %}
      </li>
      {% endif %}
      <li class="nav-item">
        {{link(url_for("repo.summary",
          owner=repo.owner.canonical_name,
          repo=repo.name), "summary")}}
      </li>
      <li class="nav-item">
        {{link(url_for("repo.tree",
          owner=repo.owner.canonical_name,
          repo=repo.name), "tree", ["blob"])}}
      </li>
      <li class="nav-item">
        {{link(url_for("repo.log",
          owner=repo.owner.canonical_name,
          repo=repo.name), "log")}}
      </li>
      <li class="nav-item">
        {{link(url_for("repo.refs",
          owner=repo.owner.canonical_name,
          repo=repo.name), "refs")}}
      </li>
      {% if len(licenses) > 0 %}
      <li class="nav-item">
        {{link(url_for("repo.licenses",
          owner=repo.owner.canonical_name,
          repo=repo.name), "licenses")}}
      </li>
      {% endif %}
      {% if current_user.id == repo.owner_id %}
      <li class="nav-item">
        {{link(url_for("manage.settings_info",
          owner_name=repo.owner.canonical_name,
          repo_name=repo.name), "settings")}}
      </li>
      {% endif %}
      {% block tabs_extra %}{% endblock %}
    </ul>
  </div>
{% endblock %}
</div>
{% block content %}{% endblock %}
<div>
  <!-- AI crawler honeypot -->
  <a
    href="/tarpit/{{repo.name}}"
    style="color: rgba(0, 0, 0, 0.1); font-size: 0.1rem"
    rel="nofollow"
  >Do not follow this link</a>
</div>
{% endblock %}